WEB-Project/WEB-Project/Models/viewmodel/Warenkorb.cs
using System;
using System.Collections.Generic;

namespace WEBProject.Models.viewmodel
{
    public class Warenkorb
    {

        public List<Article> WarenkorbKlasse { get; set; }

        public Warenkorb() : this(null) { }
        public Warenkorb(List<Article> warenkorb) {
            this.WarenkorbKlasse = warenkorb;
        }
    }
}

WEB-Project/WEB-Project/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using WEBProject.Models;
using WEBProject.Models.db;

namespace WEBProject.Controllers
{
    public class ShopController : Controller
    {
       
        private IArticleRepository articleRepository;

        public ActionResult Index()
        {
            return View ();
        }
        public ActionResult Shop()
        {
            return View();
        }
        public ActionResult DetailShop(int id)
        {

            try
            {
                articleRepository = new ArticleRepositoryDB();
                articleRepository.Open();
                Article a = articleRepository.GetArticle(id);
                return View(articleRepository.GetArticle(id));
            }
            catch (MySqlException)
            {
                return View("Message", new Message("Datenbankfehler", "", "Datenbankfehler", ""));
            }
            catch (Exception)
            {
                return View("Message", new Message("Fehler", "", "Fehler bei der Erstellung des Artikels", ""));
            } //
      
            finally
            {
                articleRepository.Close();
            }

        }





        public ActionResult Warenkorb(int id)
        {
            if ((Session["isAdmin"] != null ) || (Session["isRegisteredUser"] != null))
            {
                try
                {
                    articleRepository = new ArticleRepositoryDB();
                    articleRepository.Open();
                    List<Article> warenkorbArticles = new List<Article>();
                    warenkorbArticles.Add(articleRepository.GetArticle(id));
                    return View(warenkorbArticles);
                }
                catch (MySqlException)
                {
                    return View("Message", new Message("Datenbankfehler", "", "Datenbankfehler", ""));
                }
                catch (Exception)
                {
                    return View("Message", new Message("Fehler", "", "Fehler bei der Erstellung des Artikels", ""));
                }
                finally
                { articleRepository.Close(); }

            }
            else
            {
                return View("Login");
            }
        }
        public ActionResult ShowAllArticle()
        {
            List<Article> articles = LoadArticles();

            return View(articles);
        }
        private List<Article> LoadArticles()
        {
            if (ModelState.IsValid)
            {
                    articleRepository = new ArticleRepositoryDB();
                    articleRepository.Open();
                    List<Article> art =  articleRepository.GetAllArticles();
                    articleRepository.Close();
                
                return art;
            }
            else { return null; }
        }

        [HttpGet]
        public ActionResult InsertArticle() 
        {
            Article article = new Article();
            return View();
        }
        [HttpPost]
        public ActionResult InsertArticle(Article articleToInsert)
        {
            if (articleToInsert != null)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        articleRepository = new ArticleRepositoryDB();
                        articleRepository.Open();
                        articleRepository.InsertArticle(articleToInsert);
                    }
                    catch (MySqlException)
                    {
                        return View("Message", new Message("Datenbankfehler", "", "Datenbankfehler", ""));
                    }
                    catch (Exception)
                    {
                        return View("Message", new Message("Fehler", "", "Fehler bei der Erstellung der Artikels", ""));
                    } //
                   
                    finally
                    {
                        articleRepository.Close();
                    }


                    return View("Message", new Message("Artikel erstellung", "", "Artikel wurde erfolgreich erstellt!", ""));
                }
                else
                {
                    return View(articleToInsert);
                }
            }


            return View();
        }
    }
}

WEB-Project/WEB-Project/Views/Shop/DetailShop.cshtml
@model WEBProject.Models.Article
@{
    ViewBag.Title = "DetailShop";
}

@if (Model != null)
{
    <div id="ContainerDetailShop">
        <table>
            <tr>
                <td id="headingDS"> @Model.ArticleName<br /></td>
                @*   <td><a href="#"><img id="warenkorbAdd" src="~/images/warenkorbHinzufügen.jpg" alt="Bild" height="80px" /></a></td>*@
                <td>@Html.ActionLink("warenkorb", "Warenkorb" + "/" + @Model.ArticleID, "Shop")</td>
            </tr>
            <tr>
                <td id="writingDS"><b>ID: </b>  @Model.ArticleID<br /></td>
            </tr>
            <tr>
                <td id="writingDS"><b>Preis: </b> @Model.Price<br /></td>
            </tr>
            <tr>
                <td id="writingDS"><b>Marke: </b> @Model.Brand<br /></td>
            </tr>
            @{
                if (Model.ReleaseDate != null)
                {
                    <tr>
                        <td id="writingDS">
                            <b>Erscheinungsdatum: </b> @(((DateTime)Model.ReleaseDate).ToLongDateString())
                        </td>
                    </tr>
                }
                else
                {
                        <tr>
                            <td>kein Datum</td>
                        </tr>
                }
            }
            @{
                if (Model.Category != null)
                {
            <tr>
                <td id="writingDS">
                    <b>Kategorie: </b> @(Model.Category)
                </td>
            </tr>
                }
                else
                {
            <tr>
                <td>
                    Kein Eintrag gefunden
                </td>
            </tr>
                }

            }
        </table>
    </div>
}
    <div id="imageDS">
        @{
        string s = "/images/" + @Model.ArticleName + ".png";
        <img id="articleimg" src="@s"height="470">
        }
    </div>

<div>



</div>

                
    <style>
        #warenkorbAdd{
            padding-bottom:10px;

        }
        #ContainerDetailShop {
            height: 550px;
            width: 430px;
            position: absolute;
            margin-top: 120px;
            margin-left: 100px;
            padding-bottom: 9px;
            padding-left: 13px;
            padding-right: 13px;
            padding-top: 13px;
            float: left;

        }

        #headingDS {
            font-size:70px;
        }
        #writingDS{
            font-size:25px;
            padding-top:60px;
            border-bottom:1px solid black;

        }
        #imageDS{
            height:550px;
            width:550px;
            position:absolute;
            margin-top:100px;
            margin-right:150px;
            float:right;
            margin-left:600px;
            border: 2px solid black;
            overflow:hidden;
            
        }
        #articleimg{
        padding-top:40px;
            position:center;
            padding-right:1px;

        }
    </style>

WEB-Project/WEB-Project/Views/Shop/InsertArticle.cshtml
@model WEBProject.Models.Article

@{
    ViewBag.Title = "InsertArticle";
}

@using (Html.BeginForm())
{
    if (Convert.ToBoolean(Session["isAdmin"]) == true)
    {
        <div id="containerInsertArticle">
            <b id="headline">Insert Article</b>
            <table>

                <thead id="headerTable">

                    <tr>
                        <td id="writing" colspan="3" @Html.ValidationSummary()></td>

                    </tr>
                </thead>

                <tbody id="tableBody">
                    <tr>
                        <td id="writing">@Html.LabelFor(a => a.ArticleName, "ArticleName")</td>
                        <td id="inputBox">@Html.TextBoxFor(a => a.ArticleName)</td>
                        @*einzelne Fehlermeldung direkt beim Element anzeigen*@
                        <td>@Html.ValidationMessageFor(a => a.ArticleName)</td>
                    </tr>
                    <tr>
                        <td id="writing">@Html.LabelFor(a => a.Price, "Price")</td>
                        <td id="inputBox">@Html.TextBoxFor(a => a.Price)</td>
                        <td>@Html.ValidationMessageFor(a => a.Price)</td>
                    </tr>
                    <tr>
                        <td id="writing">@Html.LabelFor(a => a.Brand, "Brand")</td>
                        <td id="inputBox">@Html.TextBoxFor(a => a.Brand)</td>
                        <td>@Html.ValidationMessageFor(a => a.Brand)</td>
                    </tr>
                    <tr>
                        <td id="writing">@Html.LabelFor(a => a.ReleaseDate, "Release Date")</td>
                        <td id="inputBox">@Html.TextBoxFor(a => a.ReleaseDate, new { type = "date" })</td>
                        <td>@Html.ValidationMessageFor(a => a.ReleaseDate)</td>
                    </tr>
                    <tr>
                        <td id="writing">@Html.LabelFor(a => a.Category, "Category")</td>
                        <td id="inputBox">@Html.EnumDropDownListFor(a => a.Category)</td>
                        <td>@Html.ValidationMessageFor(a => a.Category)</td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input id="submit" type="submit" value="Absenden" />
                            <input id="reset" type="reset" value="Abbrechen" />

                        </td>

                    </tr>

                </tbody>

                <tfoot>
                </tfoot>
            </table>
        </div>
    }
    else{
        <p id="p1">Sie haben keine Berechtigung!</p>
    }
}
    <style>
    #containerInsertArticle {
        height: 500px;
        width: 430px;
        position: absolute;
        margin-top: 175px;
        margin-left: 500px;
        padding-bottom: 13px;
        padding-left: 13px;
        padding-right: 13px;
        padding-top: 13px;
    }

    #writing {
        font-size: larger;
    }

    #inputBox {
        height: 50px;
        width: 170px;
        font-size: larger;
    }

    #submit {
        margin-bottom: 5px;
        margin-left: 15px;
    }

    #reset {
        margin-bottom: 5px;
        margin-right: 15px;
    }

    #headline {
        font-size: larger;
        text-decoration: underline;
    }
    #p1{
        margin-top: 100px;
        margin-left: 20px;
    }
</style>

WEB-Project/WEB-Project/Views/Shop/Shop.cshtml


@{
    ViewBag.Title = "Shop";
}



<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Item 1</div>
                <div class="panel-body"><img src="~/#" class="img-responsive center-block" style="height:200px" alt="Image"></div>
                <div class="panel-footer"><button onclick="window.location.href = '';"><b> Angebot</b></button></div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Item 2</div>
                <div id ="image" class="panel-body"><img src="~/images/uhr.jpg" class="img-responsive center-block" style="height:200px" alt="Image"></div>
                <div class="panel-footer"><button onclick="window.location.href = '';"><b> Angebot</b></button></div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Item 3</div>
                <div class="panel-body"><img src="~/images/auto.jpg" class="img-responsive center-block" style="height:200px" alt="Image"></div>
                <div class="panel-footer"><button onclick="window.location.href = '';"><b> Angebot</b></button></div>
            </div>
        </div>
    </div>
</div><br>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Item 4</div>
                <div class="panel-body"><img src="~/images/auto.jpg" class="img-responsive center-block" style="height:200px" alt="Image"></div>
                <div class="panel-footer"><button onclick="window.location.href = '';"><b> Angebot</b></button></div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Item 5</div>
                <div class="panel-body"><img src="~/images/auto.jpg" class="img-responsive center-block" style="height:200px" alt="Image"></div>
                <div class="panel-footer"><button onclick="window.location.href = '';"><b> Angebot</b></button></div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Item 6</div>
                <div class="panel-body"><img src="~/images/auto.jpg" class="img-responsive center-block" style="height:200px" alt="Image"></div>
                <div class="panel-footer"><button onclick="window.location.href = '';"><b> Angebot</b></button></div>
            </div>
        </div>
    </div>
</div><br><br>


<style>
    #container {
        margin-top: 10%;
    }

    #row {
        margin-bottom: 50px;
    }
    #image{
        margin: 0 auto;
    }

    </style>

WEB-Project/WEB-Project/Views/Shop/ShowAllArticle.cshtml
@model List<WEBProject.Models.Article>
@using WEBProject.Models

@{
    ViewBag.Title = "ShowAllArticle";
}

<h2>ShowAllArticle</h2>

@if (Model != null)
{

            foreach (Article a in Model)
            {
<div id="OneArticle">
    @{
        string s = "/images/" + @a.ArticleName + ".png";
        <img id="SAAImage" src="@s">
    }
    <p id="SAAName"><b>@a.ArticleName</b></p>
    <p id="SAAPrice">@(a.Price) €</p> 
    <p id="SAALink">@Html.ActionLink("Detailsansicht", "DetailShop" + "/" + @a.ArticleID, "Shop")</p>
    <p></p>
</div>
            }
}
else
{
    <p>
        Kein Eintrag gefunden
    </p>
}


<style>
    #OneArticle{
        padding-top:5px;
        height:200px;
        width:100%;
        border-bottom: 1px solid black;
        overflow-y:hidden;
    }
    #SAAName{
    font-size:50px;
    text-align:center;
    }
    #SAAPrice{
        text-align:center;
        font-size:30px;
    }
    #SAALink {
        text-align: center;
        font-size: 20px;
    }
    #SAAImage{
        padding-bottom:1px;
        display:flex;
        margin:auto;
        float:left;
        margin-right:50px;
        width:195px;
    }

</style>

WEB-Project/WEB-Project/Views/Shop/Warenkorb.cshtml
@model List<WEBProject.Models.Article>
    @using WEBProject.Models
    @{
        ViewBag.Title = "Warenkorb";
    }
    <br /><br /><br /><br />
    @if (Model != null)
    {

        foreach (Article a in Model)
        {
            <div id="OneArticle">

                <p id="SAAName"><b>@a.ArticleName</b></p>
                <p id="SAAPrice">@(a.Price) €</p>
                <p></p>
            </div>
        }
    }
    else
    {
        <p>
            Kein Eintrag gefunden
        </p>
    }